### ISSUE TITLE
Consider using the ruby-ng PPA instead of rbenv

### ISSUE THREAD

**Issue by postmodern** [0xa/mastodon-ansible#1]
The [BrightBox ruby-ng PPA](https://launchpad.net/~brightbox/+archive/ubuntu/ruby-ng) provides a ruby2.3 package. Having ruby controlled by apt should allow for ruby security updates to be installed. Here are some example playbooks:

* https://gist.github.com/sickill/0f7433ee54af14d9fa3c
* https://gist.github.com/owainlewis/7098068
* https://galaxy.ansible.com/mtpereira/ruby/

**Comment by 0xa** [comment]
That'd be great but I'm only using Debian at the moment

**Comment by postmodern** [comment]
@0xa looks like Debian unstable and testing already have ruby 2.3 packages. Not sure if those packages are vanilla ruby packages, or have other Debian specific "modifications" that might break Rails apps.

**Comment by postmodern** [comment]
For distros where there is no package, then perhaps [ruby-build](https://github.com/rbenv/ruby-build#readme) or [ruby-install](https://github.com/postmodern/ruby-install#readme) a version of ruby into either `/usr/local` or `/opt/rubies/` might be a better alternative to rbenv.

**Comment by maxfierke** [comment]
@postmodern rbenv uses `ruby-build` IIRC

**Comment by postmodern** [comment]
Yeah, you don't need the whole shims layer, if you just need to install one system-wide version of ruby.

**Comment by 0xa** [comment]
That's all really nice but still not enough production-friendly to me...
I went with a .deb; it's faster and does not require any additional tool on each VM.
It was surprisingly easy to make one of the right version with https://github.com/bradhe/ruby-deb

**Comment by postmodern** [comment]
Will that method give you automatic security updates, a la [unattended upgrades](https://wiki.debian.org/UnattendedUpgrades)?

**Comment by 0xa** [comment]
No, but neither do all the other methods requiring compilation.
I don't want to use testing/unstable; I'll consider the PPA if I move to Ubuntu (or feel free to send an Ubuntu version).
